version: '3.8'

services:
  easevote-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: easevote-app
    expose:
      - "5000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: easevote.backend
        fluentd-async-connect: "true"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: easevote-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
    depends_on:
      - easevote-backend
    restart: unless-stopped

  fluentd:
    image: fluent/fluentd:v1.16-1
    container_name: easevote-fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./fluentd/logs:/fluentd/log
    restart: unless-stopped
