# Receive logs from Docker daemon
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

# Process logs tagged with 'easevote.backend'
<match easevote.backend>
  @type stdout # Modify this to send logs to CloudWatch, Mongo, etc.
</match>
